### ISSUE TITLE
Custom tag with optional filter

### ISSUE THREAD

**Issue by sinejoe** [mozilla/nunjucks#236] opened 2014-05-21 16:48 UTC
Working on a {% firstof %} custom tag/extension which returns the first argument with a truthy value and would like for the usage to allow for an optional filter(s) following the arguments. e.g.

```
{% firstof foo, bar, snafu | capitalize %}
-- or --
{% firstof(foo, bar, snafu) | capitalize %}
```
Here is the extension without the filter capability...

```
  function FirstOf() {

    this.tags = ['firstof'];

    this.parse = function(parser, nodes, lexer) {
      var token = parser.nextToken();
      var args = parser.parseSignature(null);
      parser.advanceAfterBlockEnd(token.value);
      return new nodes.CallExtension(this, 'run', args);
    }

    this.run = function(context) {
      if (arguments.length === 1) {
        return '';
      }
      var args = Array.prototype.slice.call(arguments, 1)
      return _.find(args, function(val) { return val })
    }

  }
```

Seems the parseFilter method needs to be incorporated here but having a hard time understanding how to do so. Any pointers would be much appreciated.

Thanks!

**Comment by carljm** [comment] 2015-12-14 20:26
Closing as dupe of #598.

**Closed by carljm** 2015-12-14 20:26 UTC
