### ISSUE TITLE
Custom tags - How to get unparsed content

### ISSUE THREAD

**Issue by imjoshholloway** [mozilla/nunjucks#373] opened 2015-02-17 13:00 UTC
I'm trying to create an extension that allows me to parse the block using an isolated context but I'm struggling to figure out how to do it.

Basically, I'm trying to be able to create custom tags so that I can do things like this in the template:

```
{% pages({limit: 5}) %}
        <p>{{page.name}}</p>
{% endpages %}
```

```
...

function PagesExtension() {
    this.tags = ['pages'];

    this.parse = function(parser, nodes, lexer) {
        // get the tag token
        var tok = parser.nextToken();

        // parse the args and move after the block end. passing true
        // as the second arg is required if there are no parentheses
        var args = parser.parseSignature(null);
        parser.advanceAfterBlockEnd(tok.value);

        // parse the body and move after block end
        var body = parser.parseUntilBlocks('endpages');

        parser.advanceAfterBlockEnd();

        return new nodes.CallExtensionAsync(this, 'run', args, [body]);
    };

    this.run = function(context, params, body, callback) {
        var block = body() // would be the unparsed template from within the block e.g: "<p>{{page.name}}</p>";
        var tmpl = new nunjucks.compile(block);

        db.getPages(params, function (err, pages) {
            if (err) {
                 return callback(err, null);
            }
            var resp = pages.map(function (page) {
                return tmpl.render({page: page});
            });
            callback(null, resp.join(''));
        }, 500);
       }); 
    };
};

env.addExtension('PagesExtension', new PagesExtension());
...
```

If I remove the `var block = body()` and replace it with `var block = '<p>{{page.name}}</p>';` it works absolutely fine so it's purely that I need a way to get the unparsed string.

If anyone has any ideas / tips it would be appreciated.

**Comment by etx** [comment] 2015-02-21 17:27
Sorry I don't have any productive input on this. But I wanted to say we could really use some more docs on the parser and creating extensions with nunjucks.

**Comment by jlongster** [comment] 2015-04-29 05:16
Unfortunately it's not easy to do this, but I think it's possible.

Basically custom tags get full access to the entire parser and lexer API. We could use better documentation, but that's quite a bit of work and would need a lot of maintenance. The best thing to do right now is read the source of `parser.js` and `lexer.js`.

You need to manually parse the token list. Instead of using `parseUntilBlocks`, use parser.nextToken and continually concatenate the `tok.value` of each one. You will have to specially check for tokens of type `lexer.TOKEN_VARIABLE_START` and handle them appropriately (turning them into the raw `{{` tags). You are basically creating your own sub-language.

The reason you can't just get the raw string is because the template has already been lexed, which is necessary because it needs to know where your end tag is.

**Comment by carljm** [comment] 2015-12-14 20:16
Closing as dupe of #598.

**Closed by carljm** 2015-12-14 20:16 UTC

**Comment by boutell** [comment] 2021-02-04 13:30
If anyone is still interested, Mark Perkins seems to have solved the problem of extracting the source without writing a complete tokens-back-to-strings routine for Nunjucks that has to be maintained as tokens are added. I haven't tried his code in Nunjucks 3 yet:

https://github.com/allmarkedup/nunjucks-with/blob/master/index.js
