### ISSUE TITLE
Whitespace control with comments causing linebreak

### ISSUE THREAD

**Issue by MadLittleMods** [mozilla/nunjucks#345] opened 2015-01-02 22:42 UTC
I believe comments should not cause the [whitespace control characters](https://github.com/mozilla/nunjucks/issues/34) to stop at the comment block. It should extend to the outer tag ignoring the comment.

**Nunjucks template**
```
<ul>
	{# comment here causes a line break to be left between ul and first li #}
	{%- for item in itemList -%}
		<li>item</li>
	{%- endfor -%}
</ul>
```

**Current Output:**
```
<ul>
	<li>item</li><li>item</li><li>item</li></ul>
```

**Desired Output:**
```
<ul><li>item</li><li>item</li><li>item</li></ul>
```

**Comment by garygreen** [comment] 2015-01-20 13:37
Duplicate of #332

**Closed by garygreen** 2015-01-20 13:37 UTC
Labels: enhancement
