### ISSUE TITLE
How to make Webstorm IDE support nunjucks grammar?

### ISSUE THREAD

**Issue by yuyang041060120** [mozilla/nunjucks#472] opened 2015-06-30 00:35 UTC
I can not format my code by Webstorm which looks like terrible.How to fix it ?

**Comment by waynebloss** [comment] 2015-06-30 01:28
You can try making nunjucks mimic a language that WebStorm does support, by setting the [tags](https://mozilla.github.io/nunjucks/api.html#customizing-syntax) option.

**Comment by ricordisamoa** [comment] 2015-06-30 02:35
Or just use an IDE that supports Jinja2 templates. If you're stuck with JetBrains, PyCharm could suit you.

**Comment by yuyang041060120** [comment] 2015-06-30 08:36
I've tried these,but It's not much helpful!

**Comment by ricordisamoa** [comment] 2015-07-03 14:23
Duplicate of #431?

**Comment by dariuszp** [comment] 2015-07-21 08:53
That's pretty easy.

1. Configure your app to use custom extension. In my case I used *.nunj. You need custom extension so IDE can recognize template files.
2. Go to File -> Settings -> Editor -> File Types
3. Find Twig, it's identical template engine but for PHP and add custom extension. click green plus and type *.nunj. Now all *.nunj files are parsed as Twig so in the end - support Nunjucks.

Example of my configuration:
```
module.exports = function (app, nunjucks, dir) {

    app.set('views', dir.views);
    app.set('view engine', 'nunj');
    app.set('view cache', app.get('env') === 'production');
    nunjucks.configure('views', {
        autoescape: true,
        express: app
    });

    app.use(function (req, res, next) {
        res.locals.user = req.session.user || false;
        next();
    });

};
```

Works like a charm :-) I switched from Swig that is no longer maintained to this one in no time.

**Comment by yuyang041060120** [comment] 2015-07-22 06:02
I can't find Twig. All my files started with T are there.
![image 1](https://cloud.githubusercontent.com/assets/6648248/8818964/f6151486-3079-11e5-8fb5-b781395a00e9.png)
I can't find any Twig plugins.
![image 1](https://cloud.githubusercontent.com/assets/6648248/8818990/417377ce-307a-11e5-9c1d-09e3bc34481a.png)

**Comment by dariuszp** [comment] 2015-07-22 06:52
Oh. My bad. I use phpstorm and there is twig support by default and plugin in repository. I understand that phpstorm plugin won't work with webstorm? Then I can't help you. You can try to install plugin from disk.

**Comment by yuyang041060120** [comment] 2015-07-22 07:58
@dariuszp I download Twig from PhpStorm Plugins. Then I install it to WebStorm.I works! Wonderful !
![image 1](https://cloud.githubusercontent.com/assets/6648248/8820699/6fede502-308a-11e5-9a9c-b3cdc099a11c.png)

Thank you!

**Comment by dariuszp** [comment] 2015-07-22 09:15
I'm glad that I could help. Good luck.

**Comment by cmdelatorre** [comment] 2015-08-06 13:12
Hi there, I get the following message trying to do it: 
"Plugin Twig Support is incompatible with current installation"

ideas?

**Comment by dariuszp** [comment] 2015-08-06 15:00
Old webstorm? Can you provide any details?

**Comment by cmdelatorre** [comment] 2015-08-06 15:19
Webstorm 8.0.4

**Comment by jlongster** [comment] 2015-08-28 02:07
@cmdelatorre Please file a bug on the appropriate repo (perhaps the twig plugin?), thanks!

**Comment by jlongster** [comment] 2015-08-28 02:07
(feel free to keep discussing it here if desired, but I'd like to close the bug)

**Closed by jlongster** 2015-08-28 02:07 UTC

**Comment by cmdelatorre** [comment] 2015-08-28 12:25
Sure, no worries.

**Comment by tammyd** [comment] 2016-03-05 04:40
Just to help anyone else out who ends up here looking for an answer, I was able to download the [intellij twig plugin](https://plugins.jetbrains.com/plugin/7303?pr=idea) and install it manually into the latest webstorm. It seems to work.

**Comment by gabe-alex** [comment] 2016-04-05 18:25
Also, you don't need to download it _manually_.

You can install Twig in WebStorm from File > Settings > Plugins > Install JetBrains plugin, and then you look for "Twig Support" in the list.

**Comment by ylei0514** [comment] 2016-10-24 06:59
i found just install twig is not use,you should do this 
preference-> Editor-> File Types  find Twig (you should install before),then add *.nunjucks at the under block , then apply

Then you will find your nunjucks code changed

**Comment by MehmetNuri** [comment] 2017-06-27 12:42
![](http://i66.tinypic.com/zw1fnm.png)

**Comment by dex1n** [comment] 2018-11-26 08:41
I come from 2018 with a Mac...
In WebStorm 2018.3 for Mac, you can install Twig from WebStorm > Preferences > Plugins and then look for "Twig Support" in the marketplace. With Twig installed, you can tell it to highlight your nunjucks file through the way showed in @MehmetNuri's screenshot.
Thanks all. Meow~

**Comment by codereviewvideos** [comment] 2020-10-12 13:44
This appears to crash Webstorm 2020.3 EAP due to some missing PHP string dependency.

**Comment by pizzavore** [comment] 2022-06-26 05:00
Webstorm 2022.1.2

A suitable workaround for me was to highlight the Nunjucks (*.njk) files as if they are HTML.

Go to Settings -> Editor -> File Types 
Select "HTML" and add *.njk to the list of file extensions.

It may not be perfect, but for me, it's way better than nothing.

**Comment by benabraham** [comment] 2022-07-12 14:20
WebStorm 2022.1.3, right click on any .njk file > Associate with File Type…, choose Twig and done.

(Plugin is available from JetBrains https://plugins.jetbrains.com/plugin/7303-twig)
