### ISSUE TITLE
`self` variable

### ISSUE THREAD

**Issue by ArmorDarks** [mozilla/nunjucks#741] opened 2016-04-29 18:50 UTC
Jinja2 allows to output any block whatever-you-want times with help of special variable `self`:

http://jinja.pocoo.org/docs/dev/templates/

> If you want to print a block multiple times, you can, however, use the special `self` variable and call the block with that name:
> ```
> <title>{% block title %}{% endblock %}</title>
> <h1>{{ self.title() }}</h1>
> {% block body %}{% endblock %}
> ```

`self` variable will resolve this issue: https://github.com/mozilla/nunjucks/issues/696

**Comment by carljm** [comment] 2016-04-29 18:52
I am absolutely in favor of this, and will implement it if I can find time. However this ticket is a duplicate of #164.

**Closed by carljm** 2016-04-29 18:52 UTC

**Comment by ArmorDarks** [comment] 2016-04-29 18:53
Ouch. I searched issues for `self`, but it returned nothing. I've completely forget about #164. Sorry for duplicate.
