### ISSUE TITLE
Cannot use nunjucks as AMD module

### ISSUE THREAD

**Issue by kevinisaac** [mozilla/nunjucks#727] opened 2016-04-14 18:48 UTC
I get the following error : `Uncaught TypeError: Cannot read property 'render' of undefined` when trying to use the variable.  This is my source : 

```
define(
    ['jquery', 'underscore', 'backbone', 'nunjucks', 'text!/static/templates/snippets/account.html'],
    function($, _, Backbone, nunjucks, accountTemplate) {
        var AccountView = Backbone.View.extend({
            el: $('#main-content'),
            render: function() {
                var data = {};
                console.log(nunjucks);
                var compiledTemplate = nunjucks.render(accountTemplate, data);
                this.$el.append(compiledTemplate);
            }
        });
        return AccountView;
    }
);
```

Link to stackoverflow question : http://stackoverflow.com/questions/36631397/cannot-use-nunjucks-as-amd-module

**Comment by carljm** [comment] 2016-04-14 23:24
I think this is a dupe of #507.

**Closed by carljm** 2016-04-14 23:24 UTC
