### ISSUE TITLE
Can't pass parameters to macros

### ISSUE THREAD

**Issue by vektrom** [mozilla/nunjucks#578] opened 2015-11-06 11:27 UTC
Hello, 

Since I start use Nunjucks 2.0.1 (I come from 1.3.1) the parameters that I pass to my macros are not sent. 

For example. If I have this macro :
```
{% macro testmacro(myparam) %} 
  Myparam value: {{ myparam }} 
{% endmacro  %} 
```
And I use it:
```
{% from "partials/mymacro.html" import testmacro %} 

{{ testmacro('myvalue') }} 
```
The result is:
```
Myparam value: 
```

The parameter have not value. But if I do this:
```
{% macro testmacro(myparam = 'initial value' ) %} 
  Myparam value: {{ myparam }} 
{% endmacro  %} 
```
And I use it like the first example, that's what I get:
```
Myparam value: initial value
```

I don't know why is this happening. When I do this in 1.3.1 it works fine. 

I hope you can help me. 

PD: Sorry for my English.

**Comment by carljm** [comment] 2015-11-06 13:15
I can't reproduce this, and I have large projects working on Nunjucks 2 that use macros with arguments heavily. So there must be something more going on than what you've described here. Are you actually passing a literal string (like `'myvalue'`) as the argument to your macro? Or are you passing a variable which may actually be undefined for some reason?

Closing for now since there isn't enough information here to reproduce the problem or pursue a fix. Will gladly reopen if you can provide a minimal reproducible test case.

**Closed by carljm** 2015-11-06 13:15 UTC
