### ISSUE TITLE
Inheritance in included blocks does not work

### ISSUE THREAD

**Issue by stereoit** [mozilla/nunjucks#536] opened 2015-09-30 08:36 UTC
The inheritance does not work for included templates. I am using gulp-nunchucks-html and then viewing the page "profile.html", it contains "Define page_title", expected "Profile".

`base.html`
```html
{% include "topbar.html" %}
```

`topbar.html`
```html
{% block page_title %}Define page_title{% endblock %}
```

`profile.html`
```html
{% extends "base.html" %}
{% block page_title %}Profile{% endblock %}
```

**Comment by devoidfury** [comment] 2015-09-30 12:41
Just a quick note, duplicate of https://github.com/mozilla/nunjucks/issues/460 -- there's some discussion on this issue.

**Comment by carljm** [comment] 2015-09-30 13:52
Inheritance works fine for included templates, but an include is like a new top-level template render; the included template has its own independent inheritance hierarchy. You can have a set of included templates that all extend some base and override some blocks from it. But the included template never participates in the inheritance hierarchy from the including template. It may help to think of inheritance as being resolved "first" (before includes). 

So this is working as designed and won't be changed; that would break existing uses.

**Closed by carljm** 2015-09-30 13:52 UTC
