### ISSUE TITLE
Add "this" keyword to get the current context

### ISSUE THREAD

**Issue by callumlocke** [mozilla/nunjucks#809] opened 2016-08-17 13:08 UTC
Handlebars lets you use `this` to access the current context.

A `this` keyword would be really useful for debugging in Nunjucks:

```nunjucks
{{ this | dump }}
```

Also:

```nunjucks
{% for key, value in this %}
  // ...
{% endfor %}
```

**Comment by ArmorDarks** [comment] 2016-08-21 22:27
You can use `addGlobal` method of Environment to achieve same functionality.

**Comment by jbmoelker** [comment] 2016-09-07 11:55
Duplicate of #833. Contains a [working demo](http://plnkr.co/edit/JyyLPF?p=preview).

I believe @ArmorDarks answer is sufficient. So I'm closing this issue.

**Closed by jbmoelker** 2016-09-07 11:55 UTC

**Comment by limitlessloop** [comment] 2019-07-26 00:00
Hi, I'm  trying to replicate the example above but I get the following error when I used the above method

```bash
Cannot read property 'getVariables' of undefined
```

Any idea what I'm not doing correctly?
