### ISSUE TITLE
anyway to get `for` frame value inside custom tag? 

### ISSUE THREAD

**Issue by atian25** [mozilla/nunjucks#624] opened 2015-12-29 01:36 UTC
```
{% for item in [1,2,3] %}
  {% custom %}
{% endfor %}
```

currently, can only use as attr:

```
{% for item in [1,2,3] %}
  {% custom item=item%}
{% endfor %}
```

**Comment by atian25** [comment] 2015-12-29 03:52
after some dig, found `compileFor` / `compileIf`, but custom tag don't privode interface to compile, only `parse` and `run`

**Comment by carljm** [comment] 2016-01-04 22:51
I don't think this is really related to `for` in any way, it's a more general issue related to #497. You can access the context in a custom tag, but not the frame.

Closing as dupe of #497.

**Closed by carljm** 2016-01-04 22:51 UTC
