### ISSUE TITLE
Nunjucks multiple view directories with express

### ISSUE THREAD

**Issue by Sk1Zy** [mozilla/nunjucks#434] opened 2015-05-05 14:17 UTC
I'm trying to use nunjucks with multiple template directories in express.

```
    app.set('views', 'src/Views');

    nunjucks.configure(['src/Views', 'src/Views2'], {
        autoescape: true,
        express: app
    })

    app.set('view engine', 'html');
```

I have set up inheritance between two templates in separate directories. It is working fine but i get this error every time i load a page.
```
EDT: error loading test template:  { [Error: ENOENT, no such file or directory 'src/Views/test.html']
  errno: 34,
  code: 'ENOENT',
  path: 'src/Views/test.html',
  syscall: 'open' }
```

This test.html is located in the Views2 directory. If i try to put both the directories in the app.set() like im doing in the configure method i get this error.
```
Template render error: TypeError: Arguments to path.join must be strings
   at path.js:360:15
   at Array.filter (native)
   at Object.exports.join (path.js:358:36)
   at getPath (/home/grimurd/Documents/Repos/Kerfill-Core/node_modules/express-debug/lib/panels/template/index.js:12:21)
   at Object.module.exports.process (/home/grimurd/Documents/Repos/Kerfill-Core/node_modules/express-debug/lib/panels/template/index.js:29:34)
   at Object.panels.render (/home/grimurd/Documents/Repos/Kerfill-Core/node_modules/express-debug/lib/panels/index.js:85:32)
   at render_toolbar (/home/grimurd/Documents/Repos/Kerfill-Core/node_modules/express-debug/lib/response.js:70:37)
   at toolbar_callback (/home/grimurd/Documents/Repos/Kerfill-Core/node_modules/express-debug/lib/response.js:103:17)
   at eval (eval at <anonymous> (/home/grimurd/Documents/Repos/Kerfill-Core/node_modules/nunjucks/src/environment.js:450:24), <anonymous>:19:1)
   at b_right (eval at <anonymous> (/home/grimurd/Documents/Repos/Kerfill-Core/node_modules/nunjucks/src/environment.js:450:24), <anonymous>:39:1)
```

Defining multiple directories with the app.set('views', []) is officially supported in express as of v4.1.0 so defining it that way needs to be supported.

Anything i can do to avoid this error?

**Comment by jlongster** [comment] 2015-05-05 15:11
Try not using `app.set` and all and just passing `app` to nunjucks (which you are already doing). Are you calling `app.set('views', ...)` for a reason? Nunjucks should take care of all of this.

You aren't supposed to tell express where your templates are, you just need to tell nunjucks. The reason is that we need to know that path, and express doesn't give it to us. I don't know why express insists on dictating how templates are handled.

**Comment by Sk1Zy** [comment] 2015-05-05 16:26
Yeah, i call app.set() because otherwise i get an error on both directories. They work in both cases though. But an error comes if i don't call it because it seems like express tries to access some default directory.
```
EDT: error loading test template:  { [Error: ENOENT, no such file or directory '/home/grimurd/Documents/Repos/Kerfill-Core/views/test.html']
  errno: 34,
  code: 'ENOENT',
  path: '/home/grimurd/Documents/Repos/Kerfill-Core/views/test.html',
  syscall: 'open' }
```

**Comment by jlongster** [comment] 2015-05-08 20:47
I guess I just don't understand. In my app if I do:

```js
nunjucks.configure(['views', 'views2'], {
    autoescape: true,
    express: app,
    watch: true
});
```

Then I can happily load templates from either directory. What version of express are you using?

**Comment by jlongster** [comment] 2015-05-08 20:48
It also works if I do `app.set('view engine', 'html');`. I can just call `res.render('index')`. I can't reproduce your error.

**Comment by jmls** [comment] 2015-05-09 10:12
can you configure nunjucks directories dynamically ?

I need to be able to search a number of directories, and rather than create a nj for each potential set I would rather just change the directory array

**Comment by jmls** [comment] 2015-05-09 10:32
ok, so if I modify the searchPaths (and assuming that test/main.js exists)

```javascript
var env = new nunjucks.Environment(new nunjucks.FileSystemLoader('views'));
    
    env.render('main.js',{check:true},function(err,data) {
        console.log("ENV#1",err,data)
    });
    
    env.loaders[0].searchPaths = ['test'];

    env.render('main.js',{check:true},function(err,data) {
        console.log("ENV#2",err,data)
    });
```
env#1 says "nope, no way. nada"
env#2 says "dude, you've found it"

is this a supported "hack" ? Will it cause any problems ?

**Comment by carljm** [comment] 2015-12-14 20:14
Closing, as I'm not clear what the remaining issue is here.

**Closed by carljm** 2015-12-14 20:14 UTC
