### ISSUE TITLE
addGlobal need async version

### ISSUE THREAD

**Issue by devalexqt** [mozilla/nunjucks#1046] opened 2017-12-24 20:24 UTC
Will be amazing if addGlobal can run async code.

**Comment by devoidfury** [comment] 2018-01-08 01:52
Can you expand on that/provide example code of what you'd like to do? What's the use-case for this?

**Comment by ArmorDarks** [comment] 2018-01-08 09:53
Duplicate of https://github.com/mozilla/nunjucks/issues/819

**Comment by devalexqt** [comment] 2018-01-08 11:32
Example: get user files from DB and then render page...

**Comment by fdintino** [comment] 2018-01-17 06:01
Closing as a duplicate of #819

**Closed by fdintino** 2018-01-17 06:01 UTC
