### ISSUE TITLE
Can't use include in block

### ISSUE THREAD

**Issue by Noiwex** [mozilla/nunjucks#817] opened 2016-08-27 08:50 UTC
I came from swig, and I can't wrap my head how this syntax is invalid:
```
{% block content %}
	{% include "./index_.html" %}
{% endblock %}
```

It makes the following error:
```
expected block end in include statement
```

Why such simple thing is impossible?

**Comment by carljm** [comment] 2016-08-28 05:35
There's something else going on in your templates that you aren't showing, because including inside a block works fine in nunjucks. Can you provide complete simplest-case templates to reproduce this issue?

Closing for now, will reopen if reproducible.

**Closed by carljm** 2016-08-28 05:35 UTC

**Comment by Noiwex** [comment] 2016-08-28 13:04
layout.html
```<!DOCTYPE html>
<html>
<head>
	<meta charset = "utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=Edge">
	<meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no">
	<meta name="theme-color" content="#005bbb">
	<link rel="stylesheet" href="/static/bundle.css?__={{css_summ}}"/>
	<link rel="apple-touch-icon" href="/static/apple-touch-icon.png"/>
	<link rel="icon" href="/static/apple-touch-icon.png"/>
	<title>{% block title %}Title{% endblock %}</title>
</head>
<body>
	{% block content %}{% endblock %}
</body>
</html>```

page/index.html
```{% extends '../layout.html' %}
{% set current_page = 'servers' %}
{% block title %}NxServ{% endblock %}

{% block content %}
	{% include "./index_.html" %}
{% endblock %}```

page/index_.html
```<div class="content">
	<div class="container">
		{% include "../warning.html" %}
		<div class="cards">
			{% for el in stuff %}
				{% include "./_card.html" with el %}
			{% endfor %}
		</div>
	</div>
</div>```

Stuff like this works perfectly in swig, but not in nunjucks.

**Comment by carljm** [comment] 2016-08-28 15:53
The error here is because of `{% include "./_card.html" with el %}` syntax; this is not supported in nunjucks. The nunjucks way is to use a macro in such cases. There is no issue with using include inside a block. The "block end" that the error message refers to is the `%}` it expects to find after `"./_card.html"`, it has nothing to do with the `{% block %}` tag.

**Comment by Noiwex** [comment] 2016-08-28 19:26
Ah, I see, thank you.

**Comment by Noiwex** [comment] 2016-08-28 19:29
Though, am I welcome to add the "include with" feature?

**Comment by carljm** [comment] 2016-08-30 17:07
see #539
