### ISSUE TITLE
Separate watch from nunjucks / 100% CPU Issues

### ISSUE THREAD

**Issue by eventEmitter** [mozilla/nunjucks#289] opened 2014-10-01 12:11 UTC
Hi, the code below causes nunjucks to use 100% of one CPU core. It makes no difference if i use different template contents, different contexts or the asyc api. 

Nunjucks version: 1.1.0
Node Version: v0.10.31

    var nunjucks = require('nunjucks');

    nunjucks.renderString('my template', {});

    setTimeout(function(){}, 1000*3600);

**Comment by mattsches** [comment] 2015-03-04 16:22
I just did an upgrade from 1.1.0 to 1.2.0, and my CPU load is down to almost 0% from >100%. The issue isn't referenced in any commits, so I wondered if this has been fixed in 1.2.0?

**Comment by popomore** [comment] 2015-03-04 16:46
@mattsches chokidar has been upgraded.

**Comment by jlongster** [comment] 2015-04-28 17:19
chokidar has been upgraded again, but I still want to work on separating out the watcher

**Comment by popomore** [comment] 2015-04-28 20:19
+1

Chokidar does optional require fsevents which always compile failed, that's
too much noisy.
James Long <notifications@github.com>于2015年4月29日 周三上午1:19写道：

**Comment by jlongster** [comment] 2015-04-30 16:19
The CPU issue looks to be fixed after upgrading to a much better version of chokidar: https://github.com/mozilla/nunjucks/pull/405

I've been working on separate the watcher, but I'm not entirely sure it's a great idea anymore. Technically it's just hard -- how do I take a watcher from the user and use it? The only way to do this is to standardize an interface and force the user to load in a watcher compatible with it and install it. That's just too much work in my opinion for a feature that should be builtin.

What I think we *can* do is support multiple watchers. If someone wants to make a PR to take a `watcher` option that specifies either chokidar or some other watcher, I would be open to it

**Closed by jlongster** 2015-04-30 16:19 UTC
Labels: bug, enhancement
