### ISSUE TITLE
express Error：Error: Can't set headers after they are sent. (Express 4)

### ISSUE THREAD

**Issue by qingxiao** [mozilla/nunjucks#739] opened 2016-04-29 06:25 UTC
in any template has that:
`
{% if true %} {% include './test.html'%} {% endif%}`
test.html:
`{{ utils.test('testesttestesttestesttestest') }}`

`utils.test = function(){ syntax error }`

so will happen:
`_http_outgoing.js:346 throw new Error('Can\'t set headers after they are sent.'); ^ Error: Can't set headers after they are sent.`

please fix this bug?

**Comment by carljm** [comment] 2016-04-29 15:45
Duplicate of #652. FWIW I don't use express and don't know anything about the express integration (I would like to remove it from nunjucks and have someone provide it as a third-party package instead). So I will not be providing a fix for this; I'd be happy to merge one if it arrives in a PR.

**Closed by carljm** 2016-04-29 15:45 UTC

**Comment by qingxiao** [comment] 2016-05-03 01:59
oh, i find express/lib/response.js have that, 
```
 // default callback to respond
  done = done || function (err, str) {
    if (err) return req.next(err);
    self.send(str);
  };
```
when first render error, while call next, but in express default project app.js will render error.html,
so happen it...
