### ISSUE TITLE
Nunjucks 2.0 TypeError when creating new Environment() in browser

### ISSUE THREAD

**Issue by jamie-pate** [mozilla/nunjucks#523] opened 2015-09-18 17:44 UTC
Looks like Nunjucks 2.0 is unusable in a web browser without configuration. If it's not meant to be useable, this situation should throw a custom error message instead, indicating the issue.

The webloader doesn't check to see if the opts argument has been provided (i guess it's not optional?)
```
	var WebLoader = Loader.extend({
	    init: function(baseURL, opts) {
	        this.baseURL = baseURL || '.';

	        // By default, the cache is turned off because there's no way
	        // to "watch" templates over HTTP, so they are re-downloaded
	        // and compiled each time. (Remember, PRECOMPILE YOUR
	        // TEMPLATES in production!)
	        this.useCache = opts.useCache;

	        // We default `async` to false so that the simple synchronous
	        // API can be used when you aren't doing anything async in
	        // your templates (which is most of the time). This performs a
	        // sync ajax request, but that's ok because it should *only*
	        // happen in development. PRECOMPILE YOUR TEMPLATES.
	        this.async = opts.async;
	    },
```

but when calling new Environment(), a new WebLoader is created without the opt argument.

```
	                this.loaders = [new builtin_loaders.WebLoader('/views')];
```

**Comment by carljm** [comment] 2015-09-18 17:47
Thanks for the report, but I think this is a duplicate of #517, no?

**Closed by carljm** 2015-09-18 17:47 UTC

**Comment by jamie-pate** [comment] 2015-09-18 17:51
sorry, i searched but didn't see that

**Comment by jamie-pate** [comment] 2015-09-18 17:52
Also, feel mine's a bit more searchable ;) so at least i'm helping a bit!

**Comment by carljm** [comment] 2015-09-18 17:54
Yep, no worries! Yours also provides more details.

**Comment by jgerigmeyer** [comment] 2015-09-18 21:05
Fixed in https://github.com/mozilla/nunjucks/pull/524.
