### ISSUE TITLE
Nunjucks 1.3.0 seems to break nunjucks-slim.js

### ISSUE THREAD

**Issue by carljm** [mozilla/nunjucks#400] opened 2015-04-03 20:26 UTC
I just upgraded a site from nunjucks 1.2.0 to nunjucks 1.3.0. We precompile templates and load `nunjucks-slim.js` in the browser. Worked fine in 1.2.0, but breaks in 1.3.0 in the browser with `TypeError: loaders is undefined` on line 1834 of `nunjucks-slim.js`. (The line in question is `nunjucks.FileSystemLoader = loaders.FileSystemLoader;`, where `loaders` is earlier defined as `var loaders = modules["loaders"];`)

**Comment by jlongster** [comment] 2015-04-03 20:34
I'm on it. This is why releases scare me!

**Comment by carljm** [comment] 2015-04-03 20:36
No worries, easy to notice in dev and roll back before any harm is done :-) Thanks for working on it!

**Comment by dav-** [comment] 2015-04-03 20:41
I'm having the same issue in the standard `nunjucks` browser bundle:
`nunjucks.js:5185 Uncaught TypeError: Cannot read property 'FileSystemLoader' of undefined`

where line 5185 is:
`nunjucks.FileSystemLoader = loaders.FileSystemLoader;`

**Comment by jlongster** [comment] 2015-04-03 20:42
Yeah, something totally broke it. I'll fix it asap. The issue isn't clear at first glance.

**Comment by dav-** [comment] 2015-04-03 20:43
@jlongster Sure thing! I just happened to do a bower update right after you released 1.3.0. Take your time, and thanks!

**Comment by jlongster** [comment] 2015-04-03 20:47
@dav- oh, bower, I've been forgetting to update the version in bower.json. How did you get the new version without me publishing there? I still don't know much about bower.

**Comment by jlongster** [comment] 2015-04-03 20:51
Should be fixed in https://github.com/mozilla/nunjucks/commit/0564714057dabcb057a415306e56662a4135d77c and I cut a new release. I guess I should have listened to the frontend tests? I thought they weren't working for a different reason :/

All passing now: http://mozilla.github.io/nunjucks/files/tests/browser/

**Comment by dav-** [comment] 2015-04-03 20:52
@jlongster I did a `bower list`, saw that version 1.3.0 was available (not sure how Bower knew that if you didn't publish it), updated my `bower.json` to require `~1.3.0`, and did a `bower update nunjucks`.

Here was the output of `bower list`:

    $ bower list
    bower check-new     Checking for new versions of the project dependencies..
    frontend#0.1.0 /Users/***/***/***
    ├─┬ backbone#1.1.2
    ~snip~
    ├── nunjucks#1.1.0 (latest is 1.3.0)
    ├── requirejs#2.1.15 (2.1.17 available)
    └── requirejs-text#2.0.13 (2.0.14 available)

**Closed by jlongster** 2015-04-03 20:51 UTC

**Comment by jlongster** [comment] 2015-04-03 21:10
Interesting, thanks! Maybe they pull from npm now or something.

**Comment by SamyPesse** [comment] 2015-04-03 21:14
No, bower is using github and tags, they are storing nothing.

On Friday, April 3, 2015, James Long <notifications@github.com> wrote:

> Interesting, thanks! Maybe they pull from npm now or something.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/nunjucks/issues/400#issuecomment-89421263>.
>


-- 
Sent from Gmail Mobile

**Comment by jgerigmeyer** [comment] 2015-04-03 21:18
@jlongster I think it's because the tag for this release is ``v.1.3.1`` instead of the usual ``v1.3.1``?

**Comment by dav-** [comment] 2015-04-03 21:24
@jgerigmeyer Yeah, that looks like a typo to me. I can't currently get 1.3.1 via bower. 

    $ bower info nunjucks
    bower not-cached    git://github.com/mozilla/nunjucks.git#*
    bower resolve       git://github.com/mozilla/nunjucks.git#*
    bower download      https://github.com/mozilla/nunjucks/archive/v1.3.0.tar.gz
    bower extract       nunjucks#* archive.tar.gz
    bower mismatch      Version declared in the json (1.0.5) is different than the resolved one (1.3.0)
    bower resolved      git://github.com/mozilla/nunjucks.git#1.3.0

    {
      name: 'nunjucks',
      version: '1.3.0',
      main: 'browser/nunjucks.min.js',
      ignore: [
        'Makefile',
        'package.json',
        'tests',
        'src',
        'docs',
        'bin',
        'index.js'
      ],
      keywords: [
        'jinja',
        'template',
        'templates',
        'templating',
        'browser'
      ],
      homepage: 'https://github.com/mozilla/nunjucks'
    }

    Available versions:
      - 1.3.0
      - 1.2.0
      - 1.1.0
      - 1.0.7
      - 1.0.6
      ...

**Comment by jlongster** [comment] 2015-04-03 21:40
Oh yikes! That is a typo. I guess I'll have to make another release.

**Comment by jlongster** [comment] 2015-04-03 21:45
Ok, fixed it about pushed out v1.3.3. Let me know if you have problems getting it.

**Comment by dav-** [comment] 2015-04-03 21:49
@jlongster Nice, I can see it in bower now! Unfortunately it looks like you forgot to bump the `bower.json` version to 1.3.3 :sob:
