### ISSUE TITLE
How to use browserify + nunjucks precompiled templates in a backbone app?

### ISSUE THREAD

**Issue by codefx9** [mozilla/nunjucks#603] opened 2015-12-07 22:57 UTC
I am trying to use nunjucks in a backbone app with browserify. My setup is pretty standard. I have tried it two different ways:

1. Using nunjuckify: My *.nunj templates ares compiled into commonjs modules as a browserify transform step using nunjuckify. Then I try to `require` the generated modules. I am getting 'nunjucks.Environment' is not a function. 

2. Using gulp-nunjucks: I used gulp-nunjucks to bundle pre-compiled modules into a single temaplates.js file. Then I try to `require(nunjucks)` module to instantiate PrecompiledLoader. I am getting `nunjucks.PrecompiledLoader` is not a function.

In both cases, the problem seems to be that the `nunjucks`' package.json contains browser field that loads a precompiled nunjucks.js file that does not conform to the commonjs module format. As a result `require('nunjucks')` is not working.

Am I doing something wrong, as I am relatively new to all these JS stuff? Is there an example that shows how to do this correctly?

**Comment by sfrdmn** [comment] 2015-12-10 18:20
Check out #507

**Comment by carljm** [comment] 2015-12-14 19:05
Closing as dupe of #507.

**Closed by carljm** 2015-12-14 19:05 UTC
