### ISSUE TITLE
custom tag/extension calling include with custom context

### ISSUE THREAD

**Issue by TimNZ** [mozilla/nunjucks#328] opened 2014-11-26 05:41 UTC
Anyway to implement via the API this scenario?

Custom tag that accepts macro style signature and calls include, limiting to a defined context, e.g.

{% widget 'a.widget', jam = 2, butter = true %}{% endwidget %}

I know I can create the custom tag, it's calling {% include %} wrapped with a custom context.
Similar to Swig include support:
http://paularmstrong.github.io/swig/docs/tags/#include

 {% import %} is not useful here

**Comment by carljm** [comment] 2015-12-14 20:22
Closing as dupe of #598 -- I'm sure this is possible because the custom extension API is very low level, but it's also not documented well and you have to really get familiar with the parser to be able to make advanced use of it.

**Closed by carljm** 2015-12-14 20:22 UTC
