### ISSUE TITLE
Custom tags: specify context of body

### ISSUE THREAD

**Issue by nwalters512** [mozilla/nunjucks#722] opened 2016-04-06 22:23 UTC
I have the following scenario: I have a custom tag, `post`, that will be used like this:

```
{% post "post.md" %}
...block content...
{% endpost %}
```

I want `post` to load the file specified in its first argument, parse some YAML front matter, and provide the parsed data as an object in the block's context. That would let me do something like the following, assuming that I put the parsed data into the `post` object:

```
{% post "post.md" %}
  {{ post.title }}
{% endpost %}
```

I've created an extension that reads the file and parses it; that's not the issue. I can't figure out how to add the retrieved information to the context of the `post` block's body. Is this possible?

**Comment by jbmoelker** [comment] 2016-04-08 19:59
I think you have a few options:

Parse post.md before even calling `nunjucks.render` (as I don't think something like this should be template lagic):
```javascript
var post = readPostDataFromMarkdownFile('post.md');
nunjucks.render('post-template.njk', { post: post });
```

Or alternatively register and use a custom function or filter:
```html
{# using custom function #}
{% set post = readPostDataFromMarkdownFile('post.md') %}
<h1>{{ post.title }}</h1>

{# using custom filter #}
{% set post = 'post.md' | readPostDataFromMarkdownFile %}
<h1>{{ post.title }}</h1>
```

**Comment by carljm** [comment] 2016-04-15 00:23
Yeah, I agree with @jbmoelker that your best practical options probably involve "don't use a custom tag for this." That's largely because the custom tag API is limited and not well documented, and there are no active maintainers around who know it well (AFAIK). We have an issue open to improve and document the custom tag API.

That said, it _seems_ to me (from reading the example code at http://mozilla.github.io/nunjucks/api.html#custom-tags) that the `run` method of a custom tag receives the `context` object; are you not able to inject new values there?

**Comment by nwalters512** [comment] 2016-04-15 18:38
Good call, I took the approach of just passing in the parsed object in `render(...)`, it's much cleaner that way anyways. I don't know why I was so focused on making it template logic!

I'll leave it up you you guys if this should be closed or not; I solved my issue by approaching things a different way, but someone else may still want to do something like this in the future.

**Comment by carljm** [comment] 2016-04-15 18:51
I'm going to close this as a dupe of #598, and I'll make a note there that this might be one use-case to look at in a possible overhaul of the custom tag API.

**Closed by carljm** 2016-04-15 18:51 UTC
Labels: custom-tags

**Comment by AlexNodex** [comment] 2016-09-21 14:36
Just a note on this... @carljm mentioned that perhaps injecting into the context, this just does not work. If one sets the context to render a file like below.

`var output=template.render('index.html',{variables:{"foo":"bar}});`

Then lets say inside that index.html file a custom tag (extension) is called which eventualy fires the `this.run` method of the mentioned extension which has a context parameter passed to it, the values in there are immutable in that they don't propogate back up to the original variables.

The strange thing is that one can `console.log(context.ctx.variables) // {foo:"bar"}` and later on  later do 

```
context.ctx.variables.foo="HARRY";
console.log(context.ctx.variables); // {foo:"HARRY"}
```
However, inside the `index.html` template, if it extends another file, those overridden variables (foo in this case) doens't get overridden, it has the initial value it was passed in the render method.

This makes custom tags not render bottom up (collecting / mutating all possible variables before rendering can begin)

I've tried every single way I can think of to get round this and nothing touches it!

**Comment by vinnyrose** [comment] 2017-02-22 16:30
This hack seems to work, it may be able to be simplified. It would be better if this was supported:
(assumes block begin is `{%` and block end is `%}`.)
(`args...`: put in whatever args you are expecting.)

    function ContextExtension() {
        this.tags = ['context'];

        this.parse = (parser, nodes, lexer) => {
            var start = parser.tokens.index;
            var symboltok = parser.nextToken();

            var args = parser.parseSignature(null, true);
            var current = parser.tokens.index;

            // fast backup to where we started
            parser.tokens.backN(current - start);
            // slow backup to before block open
            while (parser.tokens.current() !== '{') {
                parser.tokens.back();
            }
            // clear saved peek
            parser.peeked = null;
            // peek up to block end
            var peek;
            while (peek = parser.peekToken()) {
                if (peek.type === lexer.TOKEN_BLOCK_END) {
                    break;
                }
                parser.nextToken();
            }
            // the length of the block end
            parser.tokens.backN(2);
            // fake symboltok to fool advanceAfterBlockEnd name detection in parseRaw
            parser.peeked = symboltok;
            // we are right up to the edge of end-block, so we are "in_code"
            parser.tokens.in_code = true;
            // get the raw body!
            var body = parser.parseRaw('context');

            return new nodes.CallExtension(this, 'run', args, [body]);
        };

        this.run = (context, args..., body) => {
            // custom logic ...
            var ctx = Object.assign({}, context.ctx, {
                newVar: 'new,
                overrideVar: 'override'
            });
            return new nunjucks.runtime.SafeString(env.renderString(body(), ctx));
        };
    }

**Comment by allmarkedup** [comment] 2017-10-23 21:50
I've needed this for a while, so I tweaked @vinnyrose's code above (thanks, btw!) and packaged it up as an extension here: https://github.com/allmarkedup/nunjucks-with

Any improvements most welcome ;-)
